### ISSUE TITLE
Missing implementation

### ISSUE THREAD

**Issue by delfimpandiani** [NasrinKalanat/SKG-Sym#1]
Hi there!--I just read your paper "Symbolic image detection using scene and knowledge graphs", which mentions that the implementation is publicly available in this repo. I do not see any content, however. Are you planning to upload it sometime soon? I am very interested and look forward to checking it out. Thanks

**Comment by NasrinKalanat** [comment]
Hi,
I am so glad for your interest in the project. Yes, I will put it there up to the end of next week.

**Comment by delfimpandiani** [comment]
Hi there. Any luck getting the data up? I was specifically wondering how you selected images for the clusters to get the final frequencies reported in Table 2 (e.g., fashion with a frequency of 612 images, death with 185, etc.). Do you have the implementation for that? In my implementation, I am getting much higher frequencies but I believe that your frequencies are probably much cleaner. If the implementation will not be published for now, do you at least have a listing of the image IDs that were used for each of the 53 clusters? Thank you in advance.

**Comment by NasrinKalanat** [comment]
Hi, 
The implementation is uploaded. 
You can find the details of dataset clustering in [this paper](https://people.cs.pitt.edu/~kovashka/hussain_zhang_kovashka_ads_cvpr2017.pdf).

**Comment by delfimpandiani** [comment]
Thank you so much!
